tasks:
  - init: npm install # when someone pushes new code to the repo
    command: 
      echo "starting dev server..."
      npm run dev # when someone opens a new workspace

ports:
  - port: 5173
    onOpen: open-browser