---
# For more details see https://www.gitpod.io/docs/references/gitpod-yml#tasks
tasks:
  - init: |
      echo "bud_get"
      echo "test"
    command: make

# ports:
#   - port: 5173
#     onOpen: open-browser
vscode:
  extensions:
    - eamodio.gitlens
    - llvm-vs-code-extensions.vscode-clangd
